import { Carrier, Region } from './types';

export const LOGO_URL = "https://geektime.io/wp-content/uploads/2023/08/cropped-icon-1-1.png";

export const CARRIERS: Carrier[] = [
  {
    id: 'fedex-global',
    name: 'FedEx',
    url: 'https://fedex.com/',
    description: 'FedEx is available in some countries; please check availability on their website.',
    region: Region.GLOBAL,
    flag: '🌎',
    tags: ['Global', 'Express'],
  },
  {
    id: 'usa-standard',
    name: 'USA Standard Shipping',
    url: 'http://106.53.210.204:8082/trackIndex.htm',
    description: 'USPS website updates only after arrival in US (approx 2-3 weeks). Track here for updates within China.',
    region: Region.NORTH_AMERICA,
    flag: '🇺🇸',
    tags: ['USA', 'USPS', 'Special Line'],
  },
  {
    id: 'canada-standard',
    name: 'Canada Standard Shipping',
    url: 'http://www.cn11185.com:8082/trackIndex.htm',
    description: 'Canada Post updates after arrival. Use this site for early tracking information.',
    region: Region.NORTH_AMERICA,
    flag: '🇨🇦',
    tags: ['Canada', 'Special Line'],
  },
  {
    id: 'uk-standard',
    name: 'UK Standard Shipping',
    url: 'http://120.77.221.225:8082/trackIndex.htm',
    description: 'Track on Royal Mail after arrival in UK. Shipping usually takes 2-3 weeks.',
    region: Region.EUROPE,
    flag: '🇬🇧',
    tags: ['UK', 'Royal Mail'],
  },
  {
    id: 'europe-standard',
    name: 'Europe Special Line',
    url: 'http://106.55.5.75:8082/trackIndex.htm',
    description: 'DHL tracking updates after package arrives in Europe. Usually takes 2-3 weeks.',
    region: Region.EUROPE,
    flag: '🇪🇺',
    tags: ['Europe', 'DHL', 'Triangle'],
  },
  {
    id: 'philippines-line',
    name: 'Philippines Line',
    url: 'http://120.77.221.225:8082/trackIndex.htm',
    description: 'Dedicated tracking channel for shipments to Philippines.',
    region: Region.ASIA,
    flag: '🇵🇭',
    tags: ['Philippines', 'Asia'],
  },
  {
    id: 'australia-line',
    name: 'Australia Line',
    url: 'https://www.17track.net/',
    description: 'Tracking code format: "ACWL+ ref number" (e.g., ACWL250224XXXXX).',
    region: Region.OCEANIA,
    flag: '🇦🇺',
    tags: ['Australia', 'ACWL'],
  },
  {
    id: 'nz-line',
    name: 'New Zealand Line',
    url: 'http://szahgj.rtb56.com/track_query.aspx',
    description: 'Dedicated tracking portal for New Zealand shipments.',
    region: Region.OCEANIA,
    flag: '🇳🇿',
    tags: ['New Zealand', 'RTB56'],
  },
  {
    id: 'mexico-line',
    name: 'Mexico Line',
    url: 'http://106.53.210.204:8082/trackIndex.htm',
    description: 'Special line tracking for shipments to Mexico.',
    region: Region.LATAM,
    flag: '🇲🇽',
    tags: ['Mexico', 'LATAM'],
  },
  {
    id: 'africa-line',
    name: 'Africa Line',
    url: 'http://hx.hailei2018.com:8082/trackIndex.htm',
    description: 'Specialized logistics tracking for African routes.',
    region: Region.AFRICA,
    flag: '🌍',
    tags: ['Africa', 'Special Line'],
  },
  {
    id: 'thailand-line',
    name: 'Thailand Line',
    url: 'http://120.78.5.95:9001/Home/PublicTrack',
    description: 'Regional tracking service for Thailand.',
    region: Region.ASIA,
    flag: '🇹🇭',
    tags: ['Thailand', 'Asia'],
  },
  {
    id: 'turkey-line',
    name: 'Turkey Line',
    url: 'https://tracking.nextsls.com/trace?app=66178e1873f04236e513d1ff',
    description: 'Local tracking code provided after package arrives in Turkey.',
    region: Region.MIDDLE_EAST,
    flag: '🇹🇷',
    tags: ['Turkey', 'NextSLS'],
  },
  {
    id: 'japan-sagawa',
    name: 'Japan Line',
    url: 'https://www.17track.net/',
    description: 'Select "Sagawa" as the carrier. Usually updates after arrival in Japan.',
    region: Region.ASIA,
    flag: '🇯🇵',
    tags: ['Japan', 'Sagawa'],
  },
  {
    id: 'ukraine-meest',
    name: 'Ukraine Line',
    url: 'https://www.17track.net/',
    description: 'Select "MEEST" as the carrier. Shipping usually takes about 3 weeks.',
    region: Region.EUROPE,
    flag: '🇺🇦',
    tags: ['Ukraine', 'MEEST'],
  },
  {
    id: 'israel-mena',
    name: 'Israel Line',
    url: 'http://www.mena56.com/',
    description: 'Dedicated tracking for Israel shipments via Mena56.',
    region: Region.MIDDLE_EAST,
    flag: '🇮🇱',
    tags: ['Israel', 'Mena56'],
  },
  {
    id: 'india-line',
    name: 'India Line',
    url: 'https://track.ind56.com/',
    description: 'Dedicated tracking portal for India shipments.',
    region: Region.ASIA,
    flag: '🇮🇳',
    tags: ['India', 'Ind56'],
  }
];